syntax = "proto3";

option go_package = "github.com/sadrax4/crypto-graphy";

// Service Node handles transaction processing.
service Node {
  // Service Node handles transaction processing.
  rpc HandleTransaction(Transaction) returns (None);
}

message None{}


message Block {
  Header               header      = 1;
  repeated Transaction transaction = 2;
};

message Header {
  int32 version   = 1;
  int32 height    = 2;
  bytes prev_hash = 3;
  bytes root_hash = 4;
  int64 timestamp = 5;
};

message TxInput {
  bytes  prev_tx_hash   = 1;
  uint32 prev_out_index = 2;
  bytes  public_key     = 3;
  bytes  signature      = 4;
};

message TxOutput{
  int64 amount  = 1;
  bytes address = 2;
};

message Transaction {
  int32             version = 1;
  repeated TxInput  inputs  = 2;
  repeated TxOutput ouputs  = 3;
};